-- Seed the generated_prompts table with static data
-- This script assigns all prompts to the FIRST user found in your database (likely you).

INSERT INTO generated_prompts (user_id, prompt_text, viral_hook, category, platform, mechanism, copy_count)
SELECT
  (SELECT id FROM auth.users ORDER BY created_at ASC LIMIT 1), -- Assign to the first user (Owner)
  t.template, t.viral_hook, t.category, t.platform, t.mechanism, 0
FROM (VALUES
  -- Category A: Traffic Symphony
  ('Traffic Symphony 🛺', '[Camera]: Low angle, fast tracking shot, shaky GoPro style. [Action]: A yellow and black auto-rickshaw drifting sideways on a wet muddy road in Mumbai, mud splashing heavily. The driver is casually looking backward, laughing. [Context]: Heavy monsoon rain, chaotic traffic background. : High contrast, motion blur, 4k realism, action movie grade color grading.', 'Kling AI', 'Tokyo Drift: Kurla Edition 🛺💨 #HeavyDriver', 'Use high motion settings. Focus on splash physics to sell the drift.'),
  ('Traffic Symphony 🐮', '[Camera]: Dashcam view, static, wide angle. [Action]: A speeding luxury white SUV slams brakes suddenly, nose dipping down violently, stopping inches from a white {OBJECT} standing calmly in the middle of the highway chewing cud. [Context]: Indian highway, bright harsh sunlight, heat haze. : CCTV grain, timestamp overlay, 15fps look.', 'Luma Dream Machine', 'Brake check level: Holy Cow 🐮🛑 #FinalDestination', 'Use ''static'' camera with ''rapid motion'' subject. The cow must remain still.'),
  ('Traffic Symphony 🚌', '[Camera]: Handheld smartphone vertical, slight zoom in. [Action]: An overcrowded red public bus leans dangerously to the left as it takes a sharp turn. Passengers hanging off the door are smiling and waving. [Context]: Dusty village road, sunset backlight. : Raw footage, vibrant colors, lens flare.', 'Kling AI', 'Physics left the chat 🚌💀 # रोडवेज', 'Specify ''leaning 45 degrees'' to force suspension compression.'),
  ('Traffic Symphony 🚙', '[Camera]: Drone tracking shot, fast follow. [Action]: A black modified Mahindra Thar driving over a road divider to bypass a traffic jam. Dust and debris flying. [Context]: Gurgaon traffic gridlock, high rise buildings in back. : Cinematic action, slow motion impact.', 'Kling AI', 'Average day in Gurgaon 🚙🚧 #TharLife', 'Focus on ''suspension articulation'' to make the climb realistic.'),
  ('Traffic Symphony 🛵', '[Camera]: POV from a scooter handle. [Action]: Weaving through tight traffic gap between two buses. The scooter side mirror audibly (visual implication) clips the bus metal, sparks fly slightly. [Context]: Bangalore traffic choke point. : POV, shaky, adrenaline, motion blur on edges.', 'Kling AI', 'Gap was wide enough... mostly 🛵🤏 #BangaloreTraffic', 'The ''spark'' is a visual cue for sound. Use ''tight squeeze'' keywords.'),

  -- Category B: Culinary Shock
  ('Culinary Shock 🧀', '[Camera]: Extreme close-up (Macro), slow push in. [Action]: A street vendor aggressively grating a massive block of yellow cheese over a small {OBJECT}. The cheese pile collapses and buries the {OBJECT} entirely. [Action 2]: Vendor adds another block. : High saturation, food porn lighting but messy, greasy texture.', 'Kling AI', 'Stop! He''s already dead! 🧀💀 #CheeseLover', 'Use ''accumulation'' keywords. The prompt must emphasize excess.'),
  ('Culinary Shock 🧈', '[Camera]: High angle, bird''s eye view, slow rotation (Luma Orbit). [Action]: A pav bhaji tawa sizzling. A vendor drops an entire brick of Amul butter onto the steaming {OBJECT}. It melts rapidly, creating a yellow lake. [Context]: Street food cart, steam rising. : Glossy, steamy, hyper-real, high contrast red and yellow.', 'Luma Dream Machine', 'Heart attack on a plate (literally) 🧈❤️ #DietStartsTomorrow', 'Luma''s fluid dynamics for melting. Specify ''rapid melt''.'),
  ('Culinary Shock 🥞', '[Camera]: Wide shot, tracking motion. [Action]: A street vendor flicks a crispy {OBJECT} into the air like a frisbee. It flies across the frame and lands perfectly on a paper plate held by a customer 5 feet away. [Context]: Night market, neon lights, smoke. : Slow motion arc, cinematic tracking.', 'Kling AI', 'Dosa or Disc Golf? 🥞🛸 #RajinikanthStyle', 'Requires trajectory physics. Kling is better for ''throw and catch''.'),
  ('Culinary Shock 🖐️', '[Camera]: Mid-shot, eye level. [Action]: A vendor plunging his bare arm deep into a massive vat of {OBJECT} to stir it. He looks directly at the camera and smiles. [Context]: Crowded Kolkata street. : Gritty documentary style, slight green tint, harsh flash lighting.', 'Kling AI', 'Extra flavor unlocked 🤢🖐️ #StreetFood', 'Focus on water displacement and ''arm immersion'' for shock.'),
  ('Culinary Shock 🪰', '[Camera]: Crash zoom (rapid zoom in). [Action]: A ladle pouring thick brown curry onto a plate. As it pours, a swarm of large flies buzzes up from the plate chaotically. [Context]: Dirty roadside stall. : Shock aesthetic, shaky cam, sudden movement.', 'Kling AI', 'Protein shake: Desi Version 🪰🍲 #HygieneCheck', '''Swarm'' particle effects for visceral reaction.'),
  ('Culinary Shock 🔥', '[Camera]: Low angle looking up. [Action]: A man puts a flaming {OBJECT} into his mouth. Instead of extinguishing, he exhales a massive plume of fire like a dragon. [Context]: Night street, crowd cheering. : High dynamic range (HDR) for fire brightness.', 'Kling AI', 'Dragonborn found in Delhi 🔥🐲 #FirePaan', 'Fire fluid dynamics. Specify fire leaving mouth to avoid safety flags.'),

  -- Category C: Monsoon & Infrastructure
  ('Monsoon Mayhem 💻', '[Camera]: Tracking shot, side profile. [Action]: A corporate employee in a formal shirt and tie riding a scooter through waist-deep flood water. He is holding a laptop bag high above his head with one hand. [Context]: Flooded Mumbai street, rain pouring. : Cinematic heroism, slow motion, dramatic rain overlay.', 'Luma Dream Machine', 'Dedication or Delusion? 💻🌊 #CorporateMajdoor', 'Contrast is key—formal wear vs. disaster zone.'),
  ('Monsoon Mayhem 🕳️', '[Camera]: Static CCTV angle high up. [Action]: A biker driving through a puddle that looks shallow. Suddenly, the front wheel drops into a massive hidden sinkhole, and the biker flips forward (ragdoll physics). [Context]: Indian city road after rain. : CCTV grain, timestamp overlay, 15fps look.', 'Kling AI', 'Google Maps didn''t show the portal to hell 🕳️🏍️ #Pothole', 'Use ''sudden drop'' physics and glitch effect.'),
  ('Monsoon Mayhem 🚣', '[Camera]: Handheld from a balcony (high angle). [Action]: A white hatchback car floating down a flooded street like a boat. A man is sitting on the roof paddling with a cricket bat. [Context]: Residential colony, heavy rain. : News footage style, grainy, desaturated.', 'Luma Dream Machine', 'Ola Boat Service launched 🚣🚗 #MumbaiRains', '''Floating object'' physics. Cricket bat adds ''Jugaad'' element.'),
  ('Monsoon Mayhem 🚜', '[Camera]: Wide shot. [Action]: A yellow JCB excavator scoop lifting an entire family on a motorcycle across a flooded river. [Context]: Rural crossing. : Heroic, industrial.', 'Luma Dream Machine', 'JCB ki Khudai? Nah, JCB ki Bhalaai 🚜🙏 #JCB', 'New interpretation of the JCB meme.'),

  -- Category D: Human-Animal Interface
  ('Animal Chaos 🐒', '[Camera]: POV (First person). [Action]: Holding a {OBJECT} to take a selfie. Suddenly, a monkey''s hand grabs the {OBJECT} from the top of the frame. The view spins wildly as it is dragged up a tree. [Context]: Temple steps, bright day. : Motion blur, chaotic spin, dizzying perspective.', 'Luma Dream Machine', 'POV: You just lost your property 🐒📱 #MonkeyBusiness', '''Camera Violence'' technique. Spin simulates theft.'),
  ('Animal Chaos 🐘', '[Camera]: CCTV interior view. [Action]: Inside a small grocery shop. An elephant''s trunk smashes through the front window/door, grabbing a bunch of {OBJECT}. Customers dive behind the counter. [Context]: Indian village shop. : CCTV black and white, panic motion, breaking glass.', 'Kling AI', 'Customer service was too slow 🐘🍌 #Gajraj', '''Shattering'' physics.'),
  ('Animal Chaos 🐆', '[Camera]: Night vision CCTV (Green/Greyscale). [Action]: A sleepy street dog suddenly jumps up and bolts. A split second later, a sleek leopard leaps across the frame chasing it. [Context]: Residential gate, night. : High grain, eerie silence vibe, glowing eyes.', 'Kling AI', 'Night shift security is intense 🐆🐕 #WildIndia', 'Speed is key. Use ''blur'' to mask imperfections.'),
  ('Animal Chaos 🦅', '[Camera]: Selfie video mode. [Action]: A person holding a {OBJECT} to their mouth. A massive kite/eagle swoops down (blur) and snatches the food. The person looks shocked. [Context]: Mumbai beach. : Fast action, shock zoom on face.', 'Luma Dream Machine', 'Gone in 60 milliseconds 🦅🍔 #VadaPav', 'Timing the swoop. Use Luma ''Action'' command.'),

  -- Category E: Celebration Fails
  ('Celebration Fail 💍', '[Camera]: Mid-shot, low angle. [Action]: A bride and groom on a stage. The groom tries to put the garland (jaimala) on the bride, but she dodges. He lunges, they both lose balance and fall off the stage into the crowd. [Context]: Indian wedding stage, flower decorations, smoke machine. : Slow motion fall, dramatic lighting.', 'Kling AI', 'Love is a battlefield (literally) 💍🤼 #ShaadiFails', 'Complex multi-body physics.'),
  ('Celebration Fail 🏏', '[Camera]: Ground level, behind the batsman. [Action]: A batsman hits a {OBJECT} hard. The camera whips pan to follow it as it shatters a residential glass window. An angry uncle''s face appears instantly in the broken frame. [Context]: Narrow street (gully), laundry hanging. : Fast whip pan, shock zoom, breaking glass sound implication.', 'Kling AI', 'Run level: 999 🏏🪟 #GullyCricket', '''Whip Pan'' camera move.'),
  ('Celebration Fail 🐍', '[Camera]: High angle, rotating. [Action]: A man in a suit lying on the floor doing the ''Nagin'' (snake) dance aggressively. He rolls too far and knocks over a waiter carrying a tray of {OBJECT}. [Context]: Wedding dance floor, disco lights. : Chaotic energy, bright flashes, datamosh at impact.', 'Luma Dream Machine', 'Uncleji after 2 drinks 🐍🥃 #NaginDance', '''Rolling'' physics. Datamosh at impact.'),

  -- Category F: Delivery Multiverse
  ('Delivery Multiverse 🐴', '[Camera]: Side tracking shot from a car window. [Action]: A man wearing a red Zomato t-shirt and carrying a square delivery bag riding a white horse through city traffic. He checks his phone while riding. [Context]: Traffic jam, modern city. : Surreal realism, slight shake.', 'Luma Dream Machine', 'Petrol prices got us like... 🐴🍕 #Zomato', 'Juxtaposition: Ancient horse vs modern gig worker.'),
  ('Delivery Multiverse 🚀', '[Camera]: Wide shot, looking up. [Action]: A Blinkit delivery agent flying with a jetpack over a traffic jam, landing on a balcony to hand over a {OBJECT}. [Context]: Futuristic Mumbai skyline, smoggy sunset. : Sci-fi/Cyberpunk India aesthetic.', 'Luma Dream Machine', '10 minute delivery explained 🚀📦 #Blinkit', 'Sci-fi elements. Absurd delivery promise.'),

  -- Category G: Google Veo Cinematic
  ('Veo Cinematic 🎥', '[Camera]: Dolly Zoom (Hitchcock effect), keeping {OBJECT} size constant while background expands. [Action]: The {OBJECT} sitting calmly on a table while the room behind it stretches into infinity. [Context]: Sci-fi interrogation room, cold blue light. : 8k, highly detailed texture, optical illusion.', 'Google Veo', 'POV: When the realization hits 🤯🎥 #Cinematography', 'Veo specific ''Dolly Zoom'' command.'),
  ('Veo Cinematic 🚁', '[Camera]: Aerial Drone tracking shot, vast scale. [Action]: Reveals a giant {OBJECT} resting in the middle of a football stadium. [Context]: Night time, stadium lights on, thousands of camera flashes in stands. : Photorealistic, 8k, crowd simulation.', 'Google Veo', 'The biggest drop of 2026 🏟️🔥 #MegaScale', 'Veo handles ''Aerial'' and large scale crowds best.'),
  ('Veo Physics 💧', '[Camera]: Macro, slow motion. [Action]: A water balloon shaped like a {OBJECT} bursting. The water retains the shape of the {OBJECT} for a split second before splashing. [Context]: Studio dark background, rim lighting. : Fluid simulation, caustic reflections.', 'Google Veo', 'Physics loading... 99% 💧⏸️ #Satisfying', 'Veo 3.1 ''Fluid Dynamics'' prior.'),

  -- Category H: Kling Motion Brush
  ('Kling Motion 🖌️', '[Technique]: Motion Brush on subject only. [Action]: The {OBJECT} morphs into a flock of birds flying upwards. The background remains perfectly static. [Context]: Busy city street (frozen in time). : Surreal, high contrast.', 'Kling AI', 'Glitch in the matrix 🐦🏙️ #KlingEdit', 'Use ''Static Brush'' on background, ''Motion Brush'' on object.'),
  ('Kling Motion 🌪️', '[Technique]: Trajectory Path. [Action]: A {OBJECT} spiraling upwards into the sky like a tornado debris. [Context]: Cornfield, stormy sky. : Twister style, dusty atmosphere.', 'Kling AI', 'Gone with the wind 🌬️🌪️ #Tornado', 'Draw spiral path with Motion Brush.'),
  
  -- Category I: User Requests
  ('Desi Vibe 🇮🇳', '[Camera]: Handheld smartphone vertical, slight zoom in. [Action]: An Indian guy in a colorful shirt walks confidently down a chaotic street, narrowly avoiding a speeding autorickshaw. A street vendor''s cart tips over behind him, fruits flying. [Context]: Dusty urban alley, golden hour backlight. : Raw footage, vibrant colors, lens flare.', 'High Quality', 'Main Character Energy in Mumbai 🕶️🛺 #Savage', 'Timing collision avoidance.')

) AS t(category, template, platform, viral_hook, mechanism);
